# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_ASPEED) += \
	ast2700a0-evb.dtb \
	ast2700-evb.dtb \
	ast2700a0-evb_ast1700a0-evb.dtb \
	ast2700a0-evb_ast1700a0-evb-cdr.dtb \
	ast2700-evb_ast1700-evb.dtb \
	ast2700-evb_ast1700-evb-cdr.dtb \
	ast2700a0-ncsi.dtb \
	ast2700-ncsi.dtb \
	ast2700a0-dcscm.dtb \
	ast2700-dcscm.dtb \
	ast2700a0-dcscm_ast1700a0-demo.dtb \
	ast2700a0-dcscm_ast1700a0-evb.dtb \
	ast2700-dcscm_ast1700-demo.dtb \
	ast2700-dcscm_ast1700-evb.dtb \
	ast2700a0-evb-256-abr.dtb \
	ast2700-evb-256-abr.dtb
